name: Deploy Products_Delete to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker permissions
      run: |
        sudo chmod 666 /var/run/docker.sock

    - name: Build Docker Image
      run: |
        docker build -t prod-delete:latest .
        sudo docker save prod-delete:latest > prod-delete.tar
        sudo chmod 644 prod-delete.tar

    - name: Transfer Docker Image
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.PRODUCTS_DELETE_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.PRODUCTS_DELETE_EC2_SSH_KEY }}
        source: prod-delete.tar
        target: /home/ec2-user/

    - name: SSH to EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.PRODUCTS_DELETE_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.PRODUCTS_DELETE_EC2_SSH_KEY }}
        script: |
          sudo docker load < /home/ec2-user/prod-delete.tar
          sudo docker stop prod-delete || true
          sudo docker rm prod-delete || true
          sudo docker run -d -p 8000:8000 --name prod-delete prod-delete:latest
          rm /home/ec2-user/prod-delete.tar
